export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const TOGGLE_LIKE_REQUEST = 'TOGGLE_LIKE_REQUEST';
export const TOGGLE_LIKE_SUCCESS = 'TOGGLE_LIKE_SUCCESS';
export const TOGGLE_LIKE_FAILURE = 'TOGGLE_LIKE_FAILURE'

export const FETCH_LIKED_PRODUCTS_REQUEST = 'FETCH_LIKED_PRODUCTS_REQUEST';
export const FETCH_LIKED_PRODUCTS_SUCCESS = 'FETCH_LIKED_PRODUCTS_SUCCESS';
export const FETCH_LIKED_PRODUCTS_FAILURE = 'FETCH_LIKED_PRODUCTS_FAILURE';

export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';

export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const UPDATE_CART_FAILURE = 'UPDATE_CART_FAILURE';
export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST';

export const CLEAR_LIKED_PRODUCTS = 'CLEAR_LIKED_PRODUCTS';
export const CLEAR_CART = 'CLEAR_CART'