import React from 'react';
import '../../styles/packingSlip.css';

const PackingSlip = ({ order }) => {
    if (!order) return <div>No order found</div>;

    return (
        <div className="packing-slip">
            <h2 className="text-center mb-4">Packing Slip</h2>

            <div className="section">
                <div><strong>Order ID:</strong> {order._id}</div>
                <div><strong>Date:</strong> {new Date(order.placedAt).toLocaleDateString()}</div>
            </div>

            <div className="section">
                <h5>Shipping Address</h5>
                <div>{order.shippingAddress.address}</div>
                <div>{order.shippingAddress.city}, {order.shippingAddress.state} - {order.shippingAddress.pincode}</div>
                <div>📞 {order.shippingAddress.phone}</div>
            </div>

            <div className="section">
                <h5>Customer Details</h5>
                <div><strong>Name:</strong> {order.userId.fullName}</div>
                <div><strong>Email:</strong> {order.userId.email}</div>
            </div>

            <div className="section">
                <h5>Items</h5>
                <table className="item-table">
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Variant</th>
                            <th>Qty</th>
                            <th>Cancelled</th>
                        </tr>
                    </thead>
                    <tbody>
                        {order.items.map((item, index) => (
                            <tr key={index} className={item.cancelled ? 'cancelled' : ''}>
                                <td>{item.product.name}</td>
                                <td>
                                    {item.selectedColor && <span>Color: {item.selectedColor}, </span>}
                                    {item.selectedSize && <span>Size: {item.selectedSize}</span>}
                                    {item.selectedRam && <span>RAM: {item.selectedRam}, </span>}
                                    {item.selectedRom && <span>ROM: {item.selectedRom}</span>}
                                </td>
                                <td>{item.quantity}</td>
                                <td>{item.cancelled ? 'Yes' : 'No'}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            <div className="section">
                <h5>Summary</h5>
                <div><strong>Items Price:</strong> ₹{order.summary.itemsPrice}</div>
                <div><strong>Discount:</strong> ₹{order.summary.discount}</div>
                <div><strong>Total Amount:</strong> ₹{order.summary.totalAmount}</div>
            </div>

            <div className="text-center mt-4">
                <small>Generated by Admin Panel • Packing use only</small>
            </div>
        </div>
    );
};

export default PackingSlip;
